version: '3'
services:
  receiver-api-lb:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - receiver-api
    ports:
      - "4000:4000"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "5672:5672"
    - "5673:5673"
    - "15672:15672"
  receiver-api:
    build: ./receiver-api
    expose:
    - "5003"
    depends_on:
    - rabbitmq
    deploy:
      replicas: 3
  consumer-db-service:
    build: ./consumer-db-service
    expose:
    - "5001"
    depends_on:
    - rabbitmq
    - sender-socket
    deploy:
      replicas: 3
  receiver-socket:
    build: ./receiver-socket
    ports:
    - "8080:8080"
    depends_on:
    - receiver-api
  sender-socket:
    build: ./sender-socket
    ports:
    - "8081:8081"
  client:
    build: ./client
    ports:
    - "3000:3000"
    depends_on:
    - receiver-socket