version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "5672:5672"
    - "5673:5673"
    - "15672:15672"
  receiver-api:
    build: ./receiver-api
    ports:
    - "5003:5003"
    depends_on:
    - rabbitmq
  consumer-db-service:
    build: ./consumer-db-service
    ports:
    - "5001:5001"
    depends_on:
    - rabbitmq
    - sender-socket
  receiver-socket:
    build: ./receiver-socket
    ports:
    - "8080:8080"
    depends_on:
    - receiver-api
  sender-socket:
    build: ./sender-socket
    ports:
    - "8081:8081"
  client:
    build: ./client
    ports:
    - "3000:3000"
    depends_on:
    - receiver-socket